name: givnotes
description: Where your notes meet beautiful UI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  avatar_glow: ^2.0.1 #remove
  bloc: ^7.0.0
  # cached_network_image: ^3.0.0-nullsafety
  cloud_firestore: ^1.0.2
  cupertino_icons: ^1.0.0
  equatable: ^2.0.0
  file_picker: ^3.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flare_flutter: ^3.0.0-nullsafety.1
  flash: ^1.5.0
  # fluro: ^2.0.3
  flutter_bloc: ^7.0.0
  # flutter_glow: ^0.2.0
  flutter_quill: ^1.2.2
  flutter_screenutil: ^5.0.0
  flutter_slidable: ^0.6.0-nullsafety.0
  # flutter_snake_navigationbar: ^0.5.0
  # flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_tags: ^1.0.0-nullsafety.1
  fluttericon: ^2.0.0
  get: ^4.1.4
  getwidget: ^2.0.1-nullsafety.4
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  # http: ^0.13.1
  hydrated_bloc: ^7.0.0
  intl: ^0.17.0
  json_annotation: ^3.1.1
  local_auth: ^1.1.0
  lottie: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  package_info: ^2.0.0
  page_transition: ^2.0.1-nullsafety.0
  path: ^1.8.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  shared_preferences: ^2.0.5
  stringprocess: ^1.0.10
  timelines: ^0.0.2+1
  # url_launcher: ^6.0.2
  uuid: ^3.0.4
  velocity_x: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  hive_generator: ^1.0.0
  json_serializable: ^3.5.1
  pedantic: ^1.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/logo/
    - assets/animations/
    - assets/fonts/
    - assets/giv_img/

  fonts:
    - family: Abril
      fonts:
        - asset: assets/fonts/Abril/Abril-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100

    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Regular.ttf
          weight: 400
    - family: SFMono
      fonts:
        - asset: assets/fonts/SFMono/SFMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFMono/SFMono-Regular.ttf
          weight: 400
    #    - family: SFPro
    #      fonts:
    #        - asset: assets/fonts/SFPro/SFProDisplay-Bold.ttf
    #          weight: 700
    #        - asset: assets/fonts/SFPro/SFProDisplay-Semibold.ttf
    #          weight: 600
    #        - asset: assets/fonts/SFPro/SFProDisplay-Medium.ttf
    #          weight: 500
    #        - asset: assets/fonts/SFPro/SFProDisplay-Regular.ttf
    #          weight: 400
    #        - asset: assets/fonts/SFPro/SFProDisplay-Light.ttf
    #          weight: 300
    #        - asset: assets/fonts/SFPro/SFProDisplay-Thin.ttf
    #          weight: 100
    ## not required
    # get_it: ^5.0.1
    # device_info: ^1.0.0
    # flutter_cupertino_settings: ^0.3.1
    # connectivity: ^2.0.2
    # flutter_riverpod: ^0.12.1
    # route_transitions: ^1.0.2
    # uuid: ^2.2.2
    # mobx: ^1.2.1+4
    # flutter_mobx: ^1.1.0+2
    ##
