name: givnotes
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons:
    firebase_auth: ^0.16.0
    google_sign_in: ^4.4.4
    font_awesome_flutter: ^8.8.1
    getwidget: ^1.1.3
    # sqflite: ^1.3.1
    sqflite_sqlcipher: ^1.1.1 
    path_provider: ^1.6.11
    intl: ^0.16.1
    focus_widget: ^1.0.2+2
    # shared_preferences: ^0.5.8
    route_transitions:
    zefyr: ^0.11.0
    quill_delta: ^1.0.2
    lottie: ^0.5.1
    flutter_snake_navigationbar: ^0.4.0+1
    google_fonts: ^1.1.0
    url_launcher: ^5.4.10
    avatar_glow: ^1.2.0
    cached_network_image: ^2.2.0+1
    permission_handler: ^5.0.1+1
    flare_flutter: ^2.0.5
    toast: ^0.1.5
    flutter_secure_storage: ^3.3.3  
    googleapis: ^0.55.0  
    file_picker: ^1.13.2
    http: ^0.12.2
    path: ^1.7.0
    hive: ^1.4.3
    hive_flutter: ^0.3.1
    uuid: ^2.2.0
    connectivity: ^0.4.9
    animations: ^1.1.2
    morpheus: ^1.2.2+1
    device_info: '>=0.4.2+7 <2.0.0'
    package_info: '>=0.4.3 <2.0.0'
    preferences: ^5.2.1
    # multi_select_item: ^1.0.3
    flutter_app_lock: ^1.3.1
    flutter_screen_lock: ^1.2.4
    local_auth: ^0.6.3+1

    # floating_search_bar: ^0.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^0.7.1
    build_runner: ^1.10.1

dependencies_override:
    sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/logo/
        - assets/animations/
    fonts:
        - family: Abril
          fonts:
              - asset: assets/fonts/Abril/Abril-Regular.ttf
        - family: Pacifico
          fonts:
              - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
        - family: TrashIcon
          fonts:
              - asset: assets/fonts/trashIcon/trash-icon.ttf
