name: givnotes
description: Where your notes meet beautiful UI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  avatar_glow: ^1.2.0
  bloc: ^6.1.1
  cached_network_image: ^2.3.3
  cupertino_icons: ^1.0.0
  device_preview: ^0.5.5
  equatable: ^1.2.5
  file_picker: ^2.1.0
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.3
  flare_flutter: ^2.0.6
  flash: ^1.3.1
  flutter_bloc: ^6.1.1
  flutter_glow: ^0.1.2
  flutter_slidable: ^0.5.7
  flutter_snake_navigationbar: ^0.4.2
  flutter_staggered_animations: ^0.1.2
  flutter_tags: ^0.4.9+1
  fluttericon: ^1.0.7
  # formz: ^0.3.2
  getwidget: ^1.2.4
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.6
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.2
  hydrated_bloc: ^6.1.0
  intl: ^0.16.1
  json_annotation: ^3.1.1
  local_auth: ^0.6.3+4
  lottie: ^0.7.0+1
  morpheus: ^1.2.2+1
  package_info: ^0.4.3+2
  path: ^1.7.0
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  quotes: ^0.0.2
  responsive_framework: ^0.0.14
  shared_preferences: ^0.5.12+4
  stringprocess: ^1.0.10
  url_launcher: ^5.7.10
  velocity_x: ^1.0.1
  zefyr: ^1.0.0-dev.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.6
  hive_generator: ^0.8.2
  json_serializable: ^3.5.1
  pedantic: ^1.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/logo/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Abril
      fonts:
        - asset: assets/fonts/Abril/Abril-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100

    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Regular.ttf
          weight: 400
    - family: SFMono
      fonts:
        - asset: assets/fonts/SFMono/SFMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFMono/SFMono-Regular.ttf
          weight: 400
    #    - family: SFPro
    #      fonts:
    #        - asset: assets/fonts/SFPro/SFProDisplay-Bold.ttf
    #          weight: 700
    #        - asset: assets/fonts/SFPro/SFProDisplay-Semibold.ttf
    #          weight: 600
    #        - asset: assets/fonts/SFPro/SFProDisplay-Medium.ttf
    #          weight: 500
    #        - asset: assets/fonts/SFPro/SFProDisplay-Regular.ttf
    #          weight: 400
    #        - asset: assets/fonts/SFPro/SFProDisplay-Light.ttf
    #          weight: 300
    #        - asset: assets/fonts/SFPro/SFProDisplay-Thin.ttf
    #          weight: 100
    ## not required
    # get_it: ^5.0.1
    # device_info: ^1.0.0
    # flutter_cupertino_settings: ^0.3.1
    # connectivity: ^2.0.2
    # flutter_riverpod: ^0.12.1
    # route_transitions: ^1.0.2
    # uuid: ^2.2.2
    # mobx: ^1.2.1+4
    # flutter_mobx: ^1.1.0+2
    ##
