name: givnotes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  font_awesome_flutter: ^8.8.1
  getwidget: ^1.2.2
  path_provider: ^1.6.11
  intl: ^0.16.1
  zefyr: ^1.0.0-dev.2.0
  quill_delta: ^2.0.0
  lottie: ^0.6.0
  flutter_snake_navigationbar: ^0.4.0+1
  google_fonts: ^1.1.0
  url_launcher: ^5.7.2
  avatar_glow: ^1.2.0
  cached_network_image: ^2.3.2+1
  permission_handler: ^5.0.1+1
  flare_flutter: ^2.0.6
  # toast: ^0.1.5
  file_picker: ^1.13.2
  http: ^0.12.2
  path: ^1.7.0

  uuid: ^2.2.0
  connectivity: ^0.4.9+3
  morpheus: ^1.2.2+1
  device_info: '>=0.4.2+7 <2.0.0'
  package_info: '>=0.4.3 <2.0.0'
  preferences: ^5.2.1
  flutter_app_lock: ^1.3.1
  local_auth: ^0.6.3+1
  flutter_staggered_animations: ^0.1.2

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  route_transitions: ^1.0.2
  flutter_tags: ^0.4.9
  # focus_widget: ^1.0.2+2
  # animations: ^1.1.2
  # flutter_secure_storage: ^3.3.3 
  #zefyr dependencies
  collection: ^1.14.6
  # url_launcher: ^5.0.0
  # quill_delta: ^2.0.0
  notus: ^1.0.0-dev.4.0
  meta: ^1.1.0
  quiver_hashcode: ^2.0.0
  characters: ^1.0.0
  sa_stateless_animation: ^1.0.3
  stringprocess: ^1.0.10
  flutter_slidable: ^0.5.7
  one_context: ^0.4.0
  flash: ^1.3.1
  # undo: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  hive_generator: ^0.8.1
  pedantic: ^1.0.0
  # dependencies_override:
  # sqflite: null
  # git:
  #   url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
  #   path: sqflite
  #   ref: fmdb_override

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/animations/
  fonts:
    - family: Abril
      fonts:
        - asset: assets/fonts/Abril/Abril-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFPro/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFPro/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFPro/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFPro/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFPro/SFProDisplay-Thin.ttf
          weight: 100
    - family: SFMono
      fonts:
        - asset: assets/fonts/SFMono/SFMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFMono/SFMono-Regular.ttf
          weight: 400
    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ZillaSlab/ZillaSlab-Regular.ttf
          weight: 400

