name: givnotes
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons:
    firebase_auth: ^0.16.0
    google_sign_in: ^4.4.4
    font_awesome_flutter:
    rflutter_alert:
    getflutter:
    sqflite:
    path_provider:
    intl:
    flutter_spinkit:
    focus_widget:
    shared_preferences:
    route_transitions:
    zefyr:
    quill_delta:
    lottie:
    flutter_snake_navigationbar:
    google_fonts:
    url_launcher: ^5.4.10
    cached_network_image:
    responsive_widgets:

    http: ^0.12.1
    # floating_search_bar: ^0.3.0
    # sticky_headers: ^0.1.8+1
    # animated_bottom_navigation_bar:
    # dotted_border:

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/logo/
        - assets/animations/
    fonts:
        - family: Abril
          fonts:
              - asset: assets/fonts/Abril/Abril-Regular.ttf
        - family: Pacifico
          fonts:
              - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
