name: givnotes
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.2
    sticky_headers: ^0.1.8+1
    firebase_auth: ^0.16.0
    google_sign_in: ^4.4.4
    font_awesome_flutter: ^8.8.1
    rflutter_alert: ^1.0.3
    getflutter: ^1.0.11
    sqflite: ^1.3.0
    path_provider:
    intl:
    flutter_spinkit:

    http: ^0.12.1
    floating_search_bar: ^0.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/logo/
        - assets/logo/icons/

    fonts:
        - family: Montserrat
          fonts:
              - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - family: SourceSansPro
          fonts:
              - asset: assets/fonts/SourceSansPro/SourceSansPro-Regular.ttf
        - family: SourceSansPro-Light
          fonts:
              - asset: assets/fonts/SourceSansPro/SourceSansPro-Light.ttf
