# ...
target 'Runner' do
    pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.0.0'
# ...

# Override Firebase SDK Version
$FirebaseSDKVersion = '8.0.0'
end